import localFont from 'next/font/local'
import "./globals.css";


const myFont = localFont({ src: '../public/fonts/Frozito.ttf' })


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>your pop</title>
        <script defer src="../vendor/Snow.js"></script>
      </head>
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
